import { CellValue, Grid } from "./types";
import { candidatesFor, SIZE } from "./validator";

/**
 * Finds the empty cell with the fewest candidates (minimum remaining value
 * heuristic). Returns -1 if the grid has no empty cells.
 */
function findBestEmptyCell(grid: Grid): { index: number; candidates: CellValue[] } | null {
  let best: { index: number; candidates: CellValue[] } | null = null;
  for (let i = 0; i < grid.length; i++) {
    if (grid[i] !== 0) continue;
    const candidates = candidatesFor(grid, i);
    if (candidates.length === 0) {
      return { index: i, candidates: [] }; // dead end, surfaces immediately
    }
    if (!best || candidates.length < best.candidates.length) {
      best = { index: i, candidates };
      if (best.candidates.length === 1) break; // can't do better than 1
    }
  }
  return best;
}

/**
 * Solves the grid in place using backtracking with MRV heuristic.
 * Returns the solved grid (new array) or null if unsolvable.
 *
 * `maxNodes` bounds the search so a pathological or invalid input grid
 * (e.g. one with conflicting given values that naive backtracking can't
 * detect as a dead end until deep into the search) can never hang the
 * process. Legitimate puzzles generated by this app (derived from a real
 * solved grid) solve in well under this budget, typically in a few
 * hundred nodes.
 */
export function solve(grid: Grid, maxNodes = 400_000): Grid | null {
  const working = [...grid];
  let nodes = 0;

  function backtrack(): boolean {
    nodes++;
    if (nodes > maxNodes) return false; // budget exceeded, bail out safely

    const cell = findBestEmptyCell(working);
    if (!cell) return true; // no empty cells left, solved
    if (cell.candidates.length === 0) return false; // dead end

    for (const value of cell.candidates) {
      working[cell.index] = value;
      if (backtrack()) return true;
      working[cell.index] = 0;
    }
    return false;
  }

  const ok = backtrack();
  return ok ? working : null;
}

/**
 * Counts number of solutions up to `limit` (default 2), used to verify
 * a puzzle has a UNIQUE solution during generation. Stops early once the
 * limit is reached for performance.
 *
 * `maxNodes` bounds the total number of backtracking steps explored so
 * that pathological grid states (rare, but possible with naive digging)
 * can never cause an unbounded/long-running search. When the budget is
 * exhausted before reaching `limit` solutions, the function returns
 * `limit + 1` to signal "treat as not-safely-unique" to the caller,
 * rather than hanging.
 */
export function countSolutions(grid: Grid, limit = 2, maxNodes = 8_000): number {
  const working = [...grid];
  let count = 0;
  let nodes = 0;
  let budgetExceeded = false;

  function recurse(): boolean {
    nodes++;
    if (nodes > maxNodes) {
      budgetExceeded = true;
      return true; // abort search
    }

    const cell = findBestEmptyCell(working);
    if (!cell) {
      count++;
      return count >= limit; // stop signal
    }
    if (cell.candidates.length === 0) return false;

    for (const value of cell.candidates) {
      working[cell.index] = value;
      if (recurse()) return true;
      working[cell.index] = 0;
    }
    return false;
  }

  recurse();
  if (budgetExceeded) return limit + 1; // signal "unsafe / not confirmed unique"
  return count;
}

export function isValidPlacementBoard(grid: Grid): boolean {
  return grid.length === SIZE * SIZE;
}
